concurrency: production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
          END
          ssh-keyscan -H "$SSH_HOST" > ~/.ssh/known_hosts
        env:
          SSH_USER: ${{ vars.SSH_USER_NAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ vars.SSH_HOST }}
      - name: Touch File
        run: |
          ssh prod 'touch ${{vars.BACKUP_PATH}}/test.txt'

