concurrency: production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v4
      - name: Install sshpass
        run: sudo apt install sshpass
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
          END
          ssh-keyscan -H "$SSH_HOST" > ~/.ssh/known_hosts
        env:
          SSH_USER: ${{ vars.SSH_USER_NAME }}
          SSH_HOST: ${{ vars.SSH_HOST }}
      - name: Touch file
        env:
          SSHPASS: ${{secrets.SSH_USER_PASSWORD}}
        run: sshpass -e ssh prod 'touch ${{vars.BACKUP_PATH}}/test2.txt'

